-- do not edit; automatically generated by UU.AG
module CondicionDeContexto where

type ListaIds = [String]
-- Decl --------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      error                : Bool
      listaVars            : ListaIds

-}
{-
   local variables for Decl.Decl:

-}
data Decl = Decl_Decl (String) (Expr)
-- semantic domain
type T_Decl = ( (Bool),(ListaIds))
-- cata
sem_Decl :: (Decl) ->
            (T_Decl)
sem_Decl ((Decl_Decl (_string) (_expr))) =
    (sem_Decl_Decl (_string) ((sem_Expr (_expr))))
sem_Decl_Decl :: (String) ->
                 (T_Expr) ->
                 (T_Decl)
sem_Decl_Decl (string_) (expr_) =
    let _lhsOerror :: (Bool)
        _lhsOlistaVars :: (ListaIds)
        _exprIerror :: (Bool)
        _exprIlistaVars :: (ListaIds)
        _exprOlistaVars :: (ListaIds)
        ( _exprIerror,_exprIlistaVars) =
            (expr_ (_exprOlistaVars))
        -- "/home/benjamin/workspace/GenericPortlet/AG/CompiladorEjemplo/CondicionDeContexto.ag"(line 31, column 19)
        (_lhsOlistaVars@_) =
            [ string_ ]
        -- "/home/benjamin/workspace/GenericPortlet/AG/CompiladorEjemplo/CondicionDeContexto.ag"(line 45, column 19)
        (_lhsOerror@_) =
            _exprIerror
        -- "/home/benjamin/workspace/GenericPortlet/AG/CompiladorEjemplo/CondicionDeContexto.ag"(line 61, column 19)
        (_exprOlistaVars@_) =
            []
    in  ( _lhsOerror,_lhsOlistaVars)
-- Decls -------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      error                : Bool
      listaVars            : ListaIds

-}
{-
   local variables for Decls.Cons:

-}
{-
   local variables for Decls.Nil:

-}
type Decls = [(Decl)]
-- semantic domain
type T_Decls = ( (Bool),(ListaIds))
-- cata
sem_Decls :: (Decls) ->
             (T_Decls)
sem_Decls (list) =
    (Prelude.foldr (sem_Decls_Cons) (sem_Decls_Nil) ((Prelude.map sem_Decl list)))
sem_Decls_Cons :: (T_Decl) ->
                  (T_Decls) ->
                  (T_Decls)
sem_Decls_Cons (hd_) (tl_) =
    let _lhsOerror :: (Bool)
        _lhsOlistaVars :: (ListaIds)
        _hdIerror :: (Bool)
        _hdIlistaVars :: (ListaIds)
        _tlIerror :: (Bool)
        _tlIlistaVars :: (ListaIds)
        ( _hdIerror,_hdIlistaVars) =
            (hd_ )
        ( _tlIerror,_tlIlistaVars) =
            (tl_ )
        -- "/home/benjamin/workspace/GenericPortlet/AG/CompiladorEjemplo/CondicionDeContexto.ag"(line 34, column 19)
        (_lhsOlistaVars@_) =
            _hdIlistaVars ++ _tlIlistaVars
        -- "/home/benjamin/workspace/GenericPortlet/AG/CompiladorEjemplo/CondicionDeContexto.ag"(line 48, column 19)
        (_lhsOerror@_) =
            _hdIerror || _tlIerror
    in  ( _lhsOerror,_lhsOlistaVars)
sem_Decls_Nil :: (T_Decls)
sem_Decls_Nil  =
    let _lhsOerror :: (Bool)
        _lhsOlistaVars :: (ListaIds)
        -- "/home/benjamin/workspace/GenericPortlet/AG/CompiladorEjemplo/CondicionDeContexto.ag"(line 35, column 19)
        (_lhsOlistaVars@_) =
            []
        -- "/home/benjamin/workspace/GenericPortlet/AG/CompiladorEjemplo/CondicionDeContexto.ag"(line 49, column 19)
        (_lhsOerror@_) =
            False
    in  ( _lhsOerror,_lhsOlistaVars)
-- Expr --------------------------------------------------------
{-
   inherited attributes:

   chained attributes:
      listaVars            : ListaIds

   synthesised attributes:
      error                : Bool

-}
{-
   local variables for Expr.Entero:

-}
{-
   local variables for Expr.Identificador:

-}
{-
   local variables for Expr.Let:

-}
data Expr = Expr_Entero (Int)
          | Expr_Identificador (String)
          | Expr_Let (Decls) (Expr)
-- semantic domain
type T_Expr = (ListaIds) ->
              ( (Bool),(ListaIds))
-- cata
sem_Expr :: (Expr) ->
            (T_Expr)
sem_Expr ((Expr_Entero (_int))) =
    (sem_Expr_Entero (_int))
sem_Expr ((Expr_Identificador (_string))) =
    (sem_Expr_Identificador (_string))
sem_Expr ((Expr_Let (_decls) (_expr))) =
    (sem_Expr_Let ((sem_Decls (_decls))) ((sem_Expr (_expr))))
sem_Expr_Entero :: (Int) ->
                   (T_Expr)
sem_Expr_Entero (int_) =
    \ _lhsIlistaVars ->
        let _lhsOerror :: (Bool)
            _lhsOlistaVars :: (ListaIds)
            -- "/home/benjamin/workspace/GenericPortlet/AG/CompiladorEjemplo/CondicionDeContexto.ag"(line 38, column 19)
            (_lhsOlistaVars@_) =
                []
            -- "/home/benjamin/workspace/GenericPortlet/AG/CompiladorEjemplo/CondicionDeContexto.ag"(line 52, column 19)
            (_lhsOerror@_) =
                False
        in  ( _lhsOerror,_lhsOlistaVars)
sem_Expr_Identificador :: (String) ->
                          (T_Expr)
sem_Expr_Identificador (string_) =
    \ _lhsIlistaVars ->
        let _lhsOerror :: (Bool)
            _lhsOlistaVars :: (ListaIds)
            -- "/home/benjamin/workspace/GenericPortlet/AG/CompiladorEjemplo/CondicionDeContexto.ag"(line 39, column 19)
            (_lhsOlistaVars@_) =
                []
            -- "/home/benjamin/workspace/GenericPortlet/AG/CompiladorEjemplo/CondicionDeContexto.ag"(line 53, column 19)
            (_lhsOerror@_) =
                not (string_ `elem` _lhsIlistaVars)
        in  ( _lhsOerror,_lhsOlistaVars)
sem_Expr_Let :: (T_Decls) ->
                (T_Expr) ->
                (T_Expr)
sem_Expr_Let (decls_) (expr_) =
    \ _lhsIlistaVars ->
        let _lhsOerror :: (Bool)
            _lhsOlistaVars :: (ListaIds)
            _declsIerror :: (Bool)
            _declsIlistaVars :: (ListaIds)
            _exprIerror :: (Bool)
            _exprIlistaVars :: (ListaIds)
            _exprOlistaVars :: (ListaIds)
            ( _declsIerror,_declsIlistaVars) =
                (decls_ )
            ( _exprIerror,_exprIlistaVars) =
                (expr_ (_exprOlistaVars))
            -- "/home/benjamin/workspace/GenericPortlet/AG/CompiladorEjemplo/CondicionDeContexto.ag"(line 40, column 19)
            (_lhsOlistaVars@_) =
                []
            -- "/home/benjamin/workspace/GenericPortlet/AG/CompiladorEjemplo/CondicionDeContexto.ag"(line 54, column 19)
            (_lhsOerror@_) =
                _declsIerror || _exprIerror
            -- "/home/benjamin/workspace/GenericPortlet/AG/CompiladorEjemplo/CondicionDeContexto.ag"(line 59, column 19)
            (_exprOlistaVars@_) =
                _declsIlistaVars ++ _lhsIlistaVars
        in  ( _lhsOerror,_lhsOlistaVars)
-- Root --------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      salida               : String

-}
{-
   local variables for Root.Root:

-}
data Root = Root_Root (Expr)
-- semantic domain
type T_Root = ( (String))
-- cata
sem_Root :: (Root) ->
            (T_Root)
sem_Root ((Root_Root (_expr))) =
    (sem_Root_Root ((sem_Expr (_expr))))
sem_Root_Root :: (T_Expr) ->
                 (T_Root)
sem_Root_Root (expr_) =
    let _lhsOsalida :: (String)
        _exprIerror :: (Bool)
        _exprIlistaVars :: (ListaIds)
        _exprOlistaVars :: (ListaIds)
        ( _exprIerror,_exprIlistaVars) =
            (expr_ (_exprOlistaVars))
        -- "/home/benjamin/workspace/GenericPortlet/AG/CompiladorEjemplo/CondicionDeContexto.ag"(line 63, column 19)
        (_exprOlistaVars@_) =
            []
        -- "/home/benjamin/workspace/GenericPortlet/AG/CompiladorEjemplo/CondicionDeContexto.ag"(line 68, column 19)
        (_lhsOsalida@_) =
            "Resultado: " ++ if not _exprIerror then "OK" else "Error"
    in  ( _lhsOsalida)


