-- do not edit; automatically generated by UU.AG
module DeclaracionNuevo where
-- Cuerpo ------------------------------------------------------
{-
   inherited attributes:
      listaIdsH            : [String]

   chained attributes:

   synthesised attributes:
      out                  : String
      resultado            : Bool

-}
{-
   local variables for Cuerpo.Cons:

-}
{-
   local variables for Cuerpo.Nil:

-}
type Cuerpo = [(Llamada)]
-- semantic domain
type T_Cuerpo = ([String]) ->
                ( (String),(Bool))
-- cata
sem_Cuerpo :: (Cuerpo) ->
              (T_Cuerpo)
sem_Cuerpo (list) =
    (Prelude.foldr (sem_Cuerpo_Cons) (sem_Cuerpo_Nil) ((Prelude.map sem_Llamada list)))
sem_Cuerpo_Cons :: (T_Llamada) ->
                   (T_Cuerpo) ->
                   (T_Cuerpo)
sem_Cuerpo_Cons (hd_) (tl_) =
    \ _lhsIlistaIdsH ->
        let _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            _hdIout :: (String)
            _hdIresultado :: (Bool)
            _hdOlistaIdsH :: ([String])
            _tlIout :: (String)
            _tlIresultado :: (Bool)
            _tlOlistaIdsH :: ([String])
            ( _hdIout,_hdIresultado) =
                (hd_ (_hdOlistaIdsH))
            ( _tlIout,_tlIresultado) =
                (tl_ (_tlOlistaIdsH))
            -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 89, column 13)
            (_lhsOout@_) =
                "    " ++  _hdIout ++ "\n" ++ _tlIout
            -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 137, column 13)
            (_lhsOresultado@_) =
                _hdIresultado && _tlIresultado
            -- copy rule (down)
            (_hdOlistaIdsH@_) =
                _lhsIlistaIdsH
            -- copy rule (down)
            (_tlOlistaIdsH@_) =
                _lhsIlistaIdsH
        in  ( _lhsOout,_lhsOresultado)
sem_Cuerpo_Nil :: (T_Cuerpo)
sem_Cuerpo_Nil  =
    \ _lhsIlistaIdsH ->
        let _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 90, column 13)
            (_lhsOout@_) =
                ""
            -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 138, column 13)
            (_lhsOresultado@_) =
                True
        in  ( _lhsOout,_lhsOresultado)
-- Decl --------------------------------------------------------
{-
   inherited attributes:
      listaIdsH            : [String]

   chained attributes:

   synthesised attributes:
      listaIds             : [String]
      out                  : String
      resultado            : Bool

-}
{-
   local variables for Decl.Decl:

-}
data Decl = Decl_Decl (Encab) (MCuerpo)
          deriving ( Show)
-- semantic domain
type T_Decl = ([String]) ->
              ( ([String]),(String),(Bool))
-- cata
sem_Decl :: (Decl) ->
            (T_Decl)
sem_Decl ((Decl_Decl (_encab) (_mCuerpo))) =
    (sem_Decl_Decl ((sem_Encab (_encab))) ((sem_MCuerpo (_mCuerpo))))
sem_Decl_Decl :: (T_Encab) ->
                 (T_MCuerpo) ->
                 (T_Decl)
sem_Decl_Decl (encab_) (mCuerpo_) =
    \ _lhsIlistaIdsH ->
        let _lhsOlistaIds :: ([String])
            _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            _encabIlistaIds :: ([String])
            _encabIout :: (String)
            _mCuerpoIout :: (String)
            _mCuerpoIresultado :: (Bool)
            _mCuerpoOlistaIdsH :: ([String])
            ( _encabIlistaIds,_encabIout) =
                (encab_ )
            ( _mCuerpoIout,_mCuerpoIresultado) =
                (mCuerpo_ (_mCuerpoOlistaIdsH))
            -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 75, column 13)
            (_lhsOout@_) =
                _encabIout ++ _mCuerpoIout
            -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 108, column 13)
            (_lhsOlistaIds@_) =
                _encabIlistaIds
            -- copy rule (up)
            (_lhsOresultado@_) =
                _mCuerpoIresultado
            -- copy rule (down)
            (_mCuerpoOlistaIdsH@_) =
                _lhsIlistaIdsH
        in  ( _lhsOlistaIds,_lhsOout,_lhsOresultado)
-- Decls -------------------------------------------------------
{-
   inherited attributes:
      listaIdsH            : [String]

   chained attributes:

   synthesised attributes:
      listaIds             : [String]
      out                  : String
      resultado            : Bool

-}
{-
   local variables for Decls.Cons:

-}
{-
   local variables for Decls.Nil:

-}
type Decls = [(Decl)]
-- semantic domain
type T_Decls = ([String]) ->
               ( ([String]),(String),(Bool))
-- cata
sem_Decls :: (Decls) ->
             (T_Decls)
sem_Decls (list) =
    (Prelude.foldr (sem_Decls_Cons) (sem_Decls_Nil) ((Prelude.map sem_Decl list)))
sem_Decls_Cons :: (T_Decl) ->
                  (T_Decls) ->
                  (T_Decls)
sem_Decls_Cons (hd_) (tl_) =
    \ _lhsIlistaIdsH ->
        let _lhsOlistaIds :: ([String])
            _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            _hdIlistaIds :: ([String])
            _hdIout :: (String)
            _hdIresultado :: (Bool)
            _hdOlistaIdsH :: ([String])
            _tlIlistaIds :: ([String])
            _tlIout :: (String)
            _tlIresultado :: (Bool)
            _tlOlistaIdsH :: ([String])
            ( _hdIlistaIds,_hdIout,_hdIresultado) =
                (hd_ (_hdOlistaIdsH))
            ( _tlIlistaIds,_tlIout,_tlIresultado) =
                (tl_ (_tlOlistaIdsH))
            -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 71, column 13)
            (_lhsOout@_) =
                "  " ++ _hdIout ++ "\n" ++ _tlIout
            -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 104, column 13)
            (_lhsOlistaIds@_) =
                _hdIlistaIds ++ _tlIlistaIds
            -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 129, column 13)
            (_lhsOresultado@_) =
                _hdIresultado && _tlIresultado
            -- copy rule (down)
            (_hdOlistaIdsH@_) =
                _lhsIlistaIdsH
            -- copy rule (down)
            (_tlOlistaIdsH@_) =
                _lhsIlistaIdsH
        in  ( _lhsOlistaIds,_lhsOout,_lhsOresultado)
sem_Decls_Nil :: (T_Decls)
sem_Decls_Nil  =
    \ _lhsIlistaIdsH ->
        let _lhsOlistaIds :: ([String])
            _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 72, column 13)
            (_lhsOout@_) =
                ""
            -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 105, column 13)
            (_lhsOlistaIds@_) =
                []
            -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 130, column 13)
            (_lhsOresultado@_) =
                True
        in  ( _lhsOlistaIds,_lhsOout,_lhsOresultado)
-- Encab -------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      listaIds             : [String]
      out                  : String

-}
{-
   local variables for Encab.Encab:

-}
data Encab = Encab_Encab (Tipo) (String)
           deriving ( Show)
-- semantic domain
type T_Encab = ( ([String]),(String))
-- cata
sem_Encab :: (Encab) ->
             (T_Encab)
sem_Encab ((Encab_Encab (_tipo) (_string))) =
    (sem_Encab_Encab ((sem_Tipo (_tipo))) (_string))
sem_Encab_Encab :: (T_Tipo) ->
                   (String) ->
                   (T_Encab)
sem_Encab_Encab (tipo_) (string_) =
    let _lhsOlistaIds :: ([String])
        _lhsOout :: (String)
        _tipoIout :: (String)
        ( _tipoIout) =
            (tipo_ )
        -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 78, column 13)
        (_lhsOout@_) =
            _tipoIout ++ string_
        -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 111, column 13)
        (_lhsOlistaIds@_) =
            [ string_ ]
    in  ( _lhsOlistaIds,_lhsOout)
-- Llamada -----------------------------------------------------
{-
   inherited attributes:
      listaIdsH            : [String]

   chained attributes:

   synthesised attributes:
      out                  : String
      resultado            : Bool

-}
{-
   local variables for Llamada.Llamada:
      error

-}
data Llamada = Llamada_Llamada (Bool) (String)
             deriving ( Show)
-- semantic domain
type T_Llamada = ([String]) ->
                 ( (String),(Bool))
-- cata
sem_Llamada :: (Llamada) ->
               (T_Llamada)
sem_Llamada ((Llamada_Llamada (_bool) (_string))) =
    (sem_Llamada_Llamada (_bool) (_string))
sem_Llamada_Llamada :: (Bool) ->
                       (String) ->
                       (T_Llamada)
sem_Llamada_Llamada (bool_) (string_) =
    \ _lhsIlistaIdsH ->
        let _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 93, column 13)
            (_lhsOout@_) =
                string_ ++ (if bool_ then "" else "()") ++ ";"
                 ++ if not _error then " <- Identificador no declarado"
                                  else ""
            -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 142, column 13)
            (_lhsOresultado@_) =
                _error
            -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 141, column 13)
            (_error@_) =
                string_ `elem` _lhsIlistaIdsH
        in  ( _lhsOout,_lhsOresultado)
-- MCuerpo -----------------------------------------------------
{-
   inherited attributes:
      listaIdsH            : [String]

   chained attributes:

   synthesised attributes:
      out                  : String
      resultado            : Bool

-}
{-
   local variables for MCuerpo.Just:

-}
{-
   local variables for MCuerpo.Nothing:

-}
type MCuerpo = (Maybe (Cuerpo))
-- semantic domain
type T_MCuerpo = ([String]) ->
                 ( (String),(Bool))
-- cata
sem_MCuerpo :: (MCuerpo) ->
               (T_MCuerpo)
sem_MCuerpo ((Prelude.Just (x))) =
    (sem_MCuerpo_Just ((sem_Cuerpo (x))))
sem_MCuerpo (Prelude.Nothing) =
    sem_MCuerpo_Nothing
sem_MCuerpo_Just :: (T_Cuerpo) ->
                    (T_MCuerpo)
sem_MCuerpo_Just (just_) =
    \ _lhsIlistaIdsH ->
        let _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            _justIout :: (String)
            _justIresultado :: (Bool)
            _justOlistaIdsH :: ([String])
            ( _justIout,_justIresultado) =
                (just_ (_justOlistaIdsH))
            -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 81, column 13)
            (_lhsOout@_) =
                "(){\n" ++ _justIout ++ "  }"
            -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 121, column 13)
            (_justOlistaIdsH@_) =
                _lhsIlistaIdsH
            -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 133, column 13)
            (_lhsOresultado@_) =
                _justIresultado
        in  ( _lhsOout,_lhsOresultado)
sem_MCuerpo_Nothing :: (T_MCuerpo)
sem_MCuerpo_Nothing  =
    \ _lhsIlistaIdsH ->
        let _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 82, column 13)
            (_lhsOout@_) =
                ";"
            -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 134, column 13)
            (_lhsOresultado@_) =
                True
        in  ( _lhsOout,_lhsOresultado)
-- Programa ----------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      out                  : String
      resultado            : Bool

-}
{-
   local variables for Programa.Clase:

-}
data Programa = Programa_Clase (String) (Decls)
              deriving ( Show)
-- semantic domain
type T_Programa = ( (String),(Bool))
-- cata
sem_Programa :: (Programa) ->
                (T_Programa)
sem_Programa ((Programa_Clase (_string) (_decls))) =
    (sem_Programa_Clase (_string) ((sem_Decls (_decls))))
sem_Programa_Clase :: (String) ->
                      (T_Decls) ->
                      (T_Programa)
sem_Programa_Clase (string_) (decls_) =
    let _lhsOout :: (String)
        _lhsOresultado :: (Bool)
        _declsIlistaIds :: ([String])
        _declsIout :: (String)
        _declsIresultado :: (Bool)
        _declsOlistaIdsH :: ([String])
        ( _declsIlistaIds,_declsIout,_declsIresultado) =
            (decls_ (_declsOlistaIdsH))
        -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 68, column 13)
        (_lhsOout@_) =
            "clase " ++ string_ ++ "{\n" ++ _declsIout ++ "}"
        -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 118, column 13)
        (_declsOlistaIdsH@_) =
            _declsIlistaIds
        -- copy rule (up)
        (_lhsOresultado@_) =
            _declsIresultado
    in  ( _lhsOout,_lhsOresultado)
-- Root --------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      out                  : IO ()

-}
{-
   local variables for Root.Root:

-}
data Root = Root_Root (Programa)
          deriving ( Show)
-- semantic domain
type T_Root = ( (IO ()))
-- cata
sem_Root :: (Root) ->
            (T_Root)
sem_Root ((Root_Root (_programa))) =
    (sem_Root_Root ((sem_Programa (_programa))))
sem_Root_Root :: (T_Programa) ->
                 (T_Root)
sem_Root_Root (programa_) =
    let _lhsOout :: (IO ())
        _programaIout :: (String)
        _programaIresultado :: (Bool)
        ( _programaIout,_programaIresultado) =
            (programa_ )
        -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 62, column 13)
        (_lhsOout@_) =
            putStrLn (_programaIout ++ "\n"
                       ++ if not _programaIresultado
                           then "Error"
                           else "Compilacion sin errores")
    in  ( _lhsOout)
-- Tipo --------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      out                  : String

-}
{-
   local variables for Tipo.Entero:

-}
{-
   local variables for Tipo.Nulo:

-}
data Tipo = Tipo_Entero 
          | Tipo_Nulo 
          deriving ( Show)
-- semantic domain
type T_Tipo = ( (String))
-- cata
sem_Tipo :: (Tipo) ->
            (T_Tipo)
sem_Tipo ((Tipo_Entero )) =
    (sem_Tipo_Entero )
sem_Tipo ((Tipo_Nulo )) =
    (sem_Tipo_Nulo )
sem_Tipo_Entero :: (T_Tipo)
sem_Tipo_Entero  =
    let _lhsOout :: (String)
        -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 85, column 13)
        (_lhsOout@_) =
            "int "
    in  ( _lhsOout)
sem_Tipo_Nulo :: (T_Tipo)
sem_Tipo_Nulo  =
    let _lhsOout :: (String)
        -- "/home/benjamin/workspace/GenericPortlet/AG/ejemplosDr/DeclaracionNuevo.ag"(line 86, column 13)
        (_lhsOout@_) =
            "void "
    in  ( _lhsOout)


