-- do not edit; automatically generated by UU.AG
module AG.ContextoAG where
-- CuerpoInterno -----------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      out                  : String

-}
{-
   local variables for CuerpoInterno.Cons:

-}
{-
   local variables for CuerpoInterno.Nil:

-}
type CuerpoInterno = [(DeclBodyPortlet)]
-- semantic domain
type T_CuerpoInterno = ( (String))
-- cata
sem_CuerpoInterno :: (CuerpoInterno) ->
                     (T_CuerpoInterno)
sem_CuerpoInterno (list) =
    (Prelude.foldr (sem_CuerpoInterno_Cons) (sem_CuerpoInterno_Nil) ((Prelude.map sem_DeclBodyPortlet list)))
sem_CuerpoInterno_Cons :: (T_DeclBodyPortlet) ->
                          (T_CuerpoInterno) ->
                          (T_CuerpoInterno)
sem_CuerpoInterno_Cons (hd_) (tl_) =
    let _lhsOout :: (String)
        _hdIout :: (String)
        _tlIout :: (String)
        ( _hdIout) =
            (hd_ )
        ( _tlIout) =
            (tl_ )
        -- "./SalidaContexto.ag"(line 70, column 13)
        (_lhsOout@_) =
            "            " ++ _hdIout ++ "\n" ++ _tlIout
    in  ( _lhsOout)
sem_CuerpoInterno_Nil :: (T_CuerpoInterno)
sem_CuerpoInterno_Nil  =
    let _lhsOout :: (String)
        -- "./SalidaContexto.ag"(line 71, column 13)
        (_lhsOout@_) =
            ""
    in  ( _lhsOout)
-- Decl --------------------------------------------------------
{-
   inherited attributes:
      listaIdsH            : [String]

   chained attributes:

   synthesised attributes:
      out                  : String
      resultado            : Bool

-}
{-
   local variables for Decl.ConsDeclSimple:

-}
{-
   local variables for Decl.ConsDefInterna:

-}
data Decl = Decl_ConsDeclSimple (DeclSimple)
          | Decl_ConsDefInterna (DefInterna)
          deriving ( Show)
-- semantic domain
type T_Decl = ([String]) ->
              ( (String),(Bool))
-- cata
sem_Decl :: (Decl) ->
            (T_Decl)
sem_Decl ((Decl_ConsDeclSimple (_declSimple))) =
    (sem_Decl_ConsDeclSimple ((sem_DeclSimple (_declSimple))))
sem_Decl ((Decl_ConsDefInterna (_defInterna))) =
    (sem_Decl_ConsDefInterna ((sem_DefInterna (_defInterna))))
sem_Decl_ConsDeclSimple :: (T_DeclSimple) ->
                           (T_Decl)
sem_Decl_ConsDeclSimple (declSimple_) =
    \ _lhsIlistaIdsH ->
        let _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            _declSimpleIout :: (String)
            _declSimpleIresultado :: (Bool)
            _declSimpleOlistaIdsH :: ([String])
            ( _declSimpleIout,_declSimpleIresultado) =
                (declSimple_ (_declSimpleOlistaIdsH))
            -- "./VerificacionContexto2.ag"(line 40, column 19)
            (_lhsOresultado@_) =
                _declSimpleIresultado
            -- "./SalidaContexto.ag"(line 58, column 19)
            (_lhsOout@_) =
                _declSimpleIout
            -- copy rule (down)
            (_declSimpleOlistaIdsH@_) =
                _lhsIlistaIdsH
        in  ( _lhsOout,_lhsOresultado)
sem_Decl_ConsDefInterna :: (T_DefInterna) ->
                           (T_Decl)
sem_Decl_ConsDefInterna (defInterna_) =
    \ _lhsIlistaIdsH ->
        let _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            _defInternaIout :: (String)
            _defInternaIresultado :: (Bool)
            _defInternaOlistaIdsH :: ([String])
            ( _defInternaIout,_defInternaIresultado) =
                (defInterna_ (_defInternaOlistaIdsH))
            -- "./VerificacionContexto2.ag"(line 41, column 19)
            (_lhsOresultado@_) =
                _defInternaIresultado
            -- "./SalidaContexto.ag"(line 59, column 19)
            (_lhsOout@_) =
                _defInternaIout
            -- copy rule (down)
            (_defInternaOlistaIdsH@_) =
                _lhsIlistaIdsH
        in  ( _lhsOout,_lhsOresultado)
-- DeclBodyPortlet ---------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      out                  : String

-}
{-
   local variables for DeclBodyPortlet.ConsDefBackground:

-}
{-
   local variables for DeclBodyPortlet.ConsDefCampos:

-}
{-
   local variables for DeclBodyPortlet.ConsDefTipo:

-}
{-
   local variables for DeclBodyPortlet.ConsDefTitle:

-}
data DeclBodyPortlet = DeclBodyPortlet_ConsDefBackground (String)
                     | DeclBodyPortlet_ConsDefCampos (DefCampos)
                     | DeclBodyPortlet_ConsDefTipo (String)
                     | DeclBodyPortlet_ConsDefTitle (String)
                     deriving ( Show)
-- semantic domain
type T_DeclBodyPortlet = ( (String))
-- cata
sem_DeclBodyPortlet :: (DeclBodyPortlet) ->
                       (T_DeclBodyPortlet)
sem_DeclBodyPortlet ((DeclBodyPortlet_ConsDefBackground (_string))) =
    (sem_DeclBodyPortlet_ConsDefBackground (_string))
sem_DeclBodyPortlet ((DeclBodyPortlet_ConsDefCampos (_defCampos))) =
    (sem_DeclBodyPortlet_ConsDefCampos ((sem_DefCampos (_defCampos))))
sem_DeclBodyPortlet ((DeclBodyPortlet_ConsDefTipo (_string))) =
    (sem_DeclBodyPortlet_ConsDefTipo (_string))
sem_DeclBodyPortlet ((DeclBodyPortlet_ConsDefTitle (_string))) =
    (sem_DeclBodyPortlet_ConsDefTitle (_string))
sem_DeclBodyPortlet_ConsDefBackground :: (String) ->
                                         (T_DeclBodyPortlet)
sem_DeclBodyPortlet_ConsDefBackground (string_) =
    let _lhsOout :: (String)
        -- "./SalidaContexto.ag"(line 76, column 22)
        (_lhsOout@_) =
            "Background" ++ " -> " ++ string_ ++ ";"
    in  ( _lhsOout)
sem_DeclBodyPortlet_ConsDefCampos :: (T_DefCampos) ->
                                     (T_DeclBodyPortlet)
sem_DeclBodyPortlet_ConsDefCampos (defCampos_) =
    let _lhsOout :: (String)
        _defCamposIout :: (String)
        ( _defCamposIout) =
            (defCampos_ )
        -- "./SalidaContexto.ag"(line 77, column 22)
        (_lhsOout@_) =
            "Field     " ++ " -> " ++ "[" ++ _defCamposIout ++ "]" ++ ";"
    in  ( _lhsOout)
sem_DeclBodyPortlet_ConsDefTipo :: (String) ->
                                   (T_DeclBodyPortlet)
sem_DeclBodyPortlet_ConsDefTipo (string_) =
    let _lhsOout :: (String)
        -- "./SalidaContexto.ag"(line 74, column 22)
        (_lhsOout@_) =
            "Tipo      " ++ " -> " ++ string_ ++ ";"
    in  ( _lhsOout)
sem_DeclBodyPortlet_ConsDefTitle :: (String) ->
                                    (T_DeclBodyPortlet)
sem_DeclBodyPortlet_ConsDefTitle (string_) =
    let _lhsOout :: (String)
        -- "./SalidaContexto.ag"(line 75, column 22)
        (_lhsOout@_) =
            "Title     " ++ " -> " ++ string_ ++ ";"
    in  ( _lhsOout)
-- DeclField ---------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      out                  : String

-}
{-
   local variables for DeclField.ConsDeclField:

-}
data DeclField = DeclField_ConsDeclField (String)
               deriving ( Show)
-- semantic domain
type T_DeclField = ( (String))
-- cata
sem_DeclField :: (DeclField) ->
                 (T_DeclField)
sem_DeclField ((DeclField_ConsDeclField (_string))) =
    (sem_DeclField_ConsDeclField (_string))
sem_DeclField_ConsDeclField :: (String) ->
                               (T_DeclField)
sem_DeclField_ConsDeclField (string_) =
    let _lhsOout :: (String)
        -- "./SalidaContexto.ag"(line 87, column 18)
        (_lhsOout@_) =
            string_
    in  ( _lhsOout)
-- DeclFields --------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      out                  : String

-}
{-
   local variables for DeclFields.Cons:

-}
{-
   local variables for DeclFields.Nil:

-}
type DeclFields = [(DeclField)]
-- semantic domain
type T_DeclFields = ( (String))
-- cata
sem_DeclFields :: (DeclFields) ->
                  (T_DeclFields)
sem_DeclFields (list) =
    (Prelude.foldr (sem_DeclFields_Cons) (sem_DeclFields_Nil) ((Prelude.map sem_DeclField list)))
sem_DeclFields_Cons :: (T_DeclField) ->
                       (T_DeclFields) ->
                       (T_DeclFields)
sem_DeclFields_Cons (hd_) (tl_) =
    let _lhsOout :: (String)
        _hdIout :: (String)
        _tlIout :: (String)
        ( _hdIout) =
            (hd_ )
        ( _tlIout) =
            (tl_ )
        -- "./SalidaContexto.ag"(line 83, column 13)
        (_lhsOout@_) =
            _hdIout ++ "," ++ _tlIout
    in  ( _lhsOout)
sem_DeclFields_Nil :: (T_DeclFields)
sem_DeclFields_Nil  =
    let _lhsOout :: (String)
        -- "./SalidaContexto.ag"(line 84, column 13)
        (_lhsOout@_) =
            ""
    in  ( _lhsOout)
-- DeclSimple --------------------------------------------------
{-
   inherited attributes:
      listaIdsH            : [String]

   chained attributes:

   synthesised attributes:
      out                  : String
      resultado            : Bool

-}
{-
   local variables for DeclSimple.ConsAddIcon:

-}
{-
   local variables for DeclSimple.ConsAddPortlet:
      errorAddPortlet

-}
{-
   local variables for DeclSimple.ConsAddTitle:

-}
data DeclSimple = DeclSimple_ConsAddIcon (String)
                | DeclSimple_ConsAddPortlet (String)
                | DeclSimple_ConsAddTitle (String)
                deriving ( Show)
-- semantic domain
type T_DeclSimple = ([String]) ->
                    ( (String),(Bool))
-- cata
sem_DeclSimple :: (DeclSimple) ->
                  (T_DeclSimple)
sem_DeclSimple ((DeclSimple_ConsAddIcon (_string))) =
    (sem_DeclSimple_ConsAddIcon (_string))
sem_DeclSimple ((DeclSimple_ConsAddPortlet (_string))) =
    (sem_DeclSimple_ConsAddPortlet (_string))
sem_DeclSimple ((DeclSimple_ConsAddTitle (_string))) =
    (sem_DeclSimple_ConsAddTitle (_string))
sem_DeclSimple_ConsAddIcon :: (String) ->
                              (T_DeclSimple)
sem_DeclSimple_ConsAddIcon (string_) =
    \ _lhsIlistaIdsH ->
        let _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            -- "./VerificacionContexto2.ag"(line 44, column 19)
            (_lhsOresultado@_) =
                True
            -- "./SalidaContexto.ag"(line 62, column 19)
            (_lhsOout@_) =
                "addIcon   " ++ " -> " ++ string_ ++ ";"
        in  ( _lhsOout,_lhsOresultado)
sem_DeclSimple_ConsAddPortlet :: (String) ->
                                 (T_DeclSimple)
sem_DeclSimple_ConsAddPortlet (string_) =
    \ _lhsIlistaIdsH ->
        let _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            -- "./VerificacionContexto2.ag"(line 47, column 35)
            (_lhsOresultado@_) =
                _errorAddPortlet
            -- "./VerificacionContexto2.ag"(line 46, column 19)
            (_errorAddPortlet@_) =
                string_ `elem` _lhsIlistaIdsH
            -- "./SalidaContexto.ag"(line 64, column 19)
            (_lhsOout@_) =
                "addPortlet" ++ " -> " ++ string_ ++ ";" ++ if not _errorAddPortlet then " <- Identificador no declarado" else ""
        in  ( _lhsOout,_lhsOresultado)
sem_DeclSimple_ConsAddTitle :: (String) ->
                               (T_DeclSimple)
sem_DeclSimple_ConsAddTitle (string_) =
    \ _lhsIlistaIdsH ->
        let _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            -- "./VerificacionContexto2.ag"(line 45, column 19)
            (_lhsOresultado@_) =
                True
            -- "./SalidaContexto.ag"(line 63, column 19)
            (_lhsOout@_) =
                "addTitle  " ++ " -> " ++ string_ ++ ";"
        in  ( _lhsOout,_lhsOresultado)
-- Decls -------------------------------------------------------
{-
   inherited attributes:
      listaIdsH            : [String]

   chained attributes:

   synthesised attributes:
      out                  : String
      resultado            : Bool

-}
{-
   local variables for Decls.Cons:

-}
{-
   local variables for Decls.Nil:

-}
type Decls = [(Decl)]
-- semantic domain
type T_Decls = ([String]) ->
               ( (String),(Bool))
-- cata
sem_Decls :: (Decls) ->
             (T_Decls)
sem_Decls (list) =
    (Prelude.foldr (sem_Decls_Cons) (sem_Decls_Nil) ((Prelude.map sem_Decl list)))
sem_Decls_Cons :: (T_Decl) ->
                  (T_Decls) ->
                  (T_Decls)
sem_Decls_Cons (hd_) (tl_) =
    \ _lhsIlistaIdsH ->
        let _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            _hdIout :: (String)
            _hdIresultado :: (Bool)
            _hdOlistaIdsH :: ([String])
            _tlIout :: (String)
            _tlIresultado :: (Bool)
            _tlOlistaIdsH :: ([String])
            ( _hdIout,_hdIresultado) =
                (hd_ (_hdOlistaIdsH))
            ( _tlIout,_tlIresultado) =
                (tl_ (_tlOlistaIdsH))
            -- "./VerificacionContexto2.ag"(line 36, column 9)
            (_lhsOresultado@_) =
                _hdIresultado && _tlIresultado
            -- "./SalidaContexto.ag"(line 54, column 13)
            (_lhsOout@_) =
                "        " ++ _hdIout ++ "\n" ++ _tlIout
            -- copy rule (down)
            (_hdOlistaIdsH@_) =
                _lhsIlistaIdsH
            -- copy rule (down)
            (_tlOlistaIdsH@_) =
                _lhsIlistaIdsH
        in  ( _lhsOout,_lhsOresultado)
sem_Decls_Nil :: (T_Decls)
sem_Decls_Nil  =
    \ _lhsIlistaIdsH ->
        let _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            -- "./VerificacionContexto2.ag"(line 37, column 9)
            (_lhsOresultado@_) =
                True
            -- "./SalidaContexto.ag"(line 55, column 13)
            (_lhsOout@_) =
                ""
        in  ( _lhsOout,_lhsOresultado)
-- DefCampos ---------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      out                  : String

-}
{-
   local variables for DefCampos.ConsCampos:

-}
data DefCampos = DefCampos_ConsCampos (DeclFields)
               deriving ( Show)
-- semantic domain
type T_DefCampos = ( (String))
-- cata
sem_DefCampos :: (DefCampos) ->
                 (T_DefCampos)
sem_DefCampos ((DefCampos_ConsCampos (_declFields))) =
    (sem_DefCampos_ConsCampos ((sem_DeclFields (_declFields))))
sem_DefCampos_ConsCampos :: (T_DeclFields) ->
                            (T_DefCampos)
sem_DefCampos_ConsCampos (declFields_) =
    let _lhsOout :: (String)
        _declFieldsIout :: (String)
        ( _declFieldsIout) =
            (declFields_ )
        -- "./SalidaContexto.ag"(line 80, column 15)
        (_lhsOout@_) =
            _declFieldsIout
    in  ( _lhsOout)
-- DefInterna --------------------------------------------------
{-
   inherited attributes:
      listaIdsH            : [String]

   chained attributes:

   synthesised attributes:
      out                  : String
      resultado            : Bool

-}
{-
   local variables for DefInterna.ConsInterno:
      errorDefInterna

-}
data DefInterna = DefInterna_ConsInterno (String) (CuerpoInterno)
                deriving ( Show)
-- semantic domain
type T_DefInterna = ([String]) ->
                    ( (String),(Bool))
-- cata
sem_DefInterna :: (DefInterna) ->
                  (T_DefInterna)
sem_DefInterna ((DefInterna_ConsInterno (_string) (_cuerpoInterno))) =
    (sem_DefInterna_ConsInterno (_string) ((sem_CuerpoInterno (_cuerpoInterno))))
sem_DefInterna_ConsInterno :: (String) ->
                              (T_CuerpoInterno) ->
                              (T_DefInterna)
sem_DefInterna_ConsInterno (string_) (cuerpoInterno_) =
    \ _lhsIlistaIdsH ->
        let _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            _cuerpoInternoIout :: (String)
            ( _cuerpoInternoIout) =
                (cuerpoInterno_ )
            -- "./VerificacionContexto2.ag"(line 51, column 28)
            (_lhsOresultado@_) =
                _errorDefInterna
            -- "./VerificacionContexto2.ag"(line 50, column 16)
            (_errorDefInterna@_) =
                string_ `elem` _lhsIlistaIdsH
            -- "./SalidaContexto.ag"(line 67, column 16)
            (_lhsOout@_) =
                string_ ++ if not _errorDefInterna then " <- Identificador no declarado" else "" ++ "\n" ++ "        <$" ++ "\n" ++ _cuerpoInternoIout ++ "\n" ++ "        $>"
        in  ( _lhsOout,_lhsOresultado)
-- Extend ------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      out                  : String

-}
{-
   local variables for Extend.ConsExtend:

-}
data Extend = Extend_ConsExtend (Type)
            deriving ( Show)
-- semantic domain
type T_Extend = ( (String))
-- cata
sem_Extend :: (Extend) ->
              (T_Extend)
sem_Extend ((Extend_ConsExtend (_type))) =
    (sem_Extend_ConsExtend ((sem_Type (_type))))
sem_Extend_ConsExtend :: (T_Type) ->
                         (T_Extend)
sem_Extend_ConsExtend (type_) =
    let _lhsOout :: (String)
        _typeIout :: (String)
        ( _typeIout) =
            (type_ )
        -- "./SalidaContexto.ag"(line 33, column 15)
        (_lhsOout@_) =
            _typeIout
    in  ( _lhsOout)
-- Import ------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      listaImports         : [String]
      out                  : String

-}
{-
   local variables for Import.IdentificadorImport:

-}
data Import = Import_IdentificadorImport (String)
            deriving ( Show)
-- semantic domain
type T_Import = ( ([String]),(String))
-- cata
sem_Import :: (Import) ->
              (T_Import)
sem_Import ((Import_IdentificadorImport (_imp))) =
    (sem_Import_IdentificadorImport (_imp))
sem_Import_IdentificadorImport :: (String) ->
                                  (T_Import)
sem_Import_IdentificadorImport (imp_) =
    let _lhsOlistaImports :: ([String])
        _lhsOout :: (String)
        -- "./CondicionesAG.ag"(line 16, column 24)
        (_lhsOlistaImports@_) =
            [imp_]
        -- "./SalidaContexto.ag"(line 26, column 24)
        (_lhsOout@_) =
            "import " ++ imp_ ++ ";"
    in  ( _lhsOlistaImports,_lhsOout)
-- Imports -----------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      listaImports         : [String]
      out                  : String

-}
{-
   local variables for Imports.Cons:

-}
{-
   local variables for Imports.Nil:

-}
type Imports = [(Import)]
-- semantic domain
type T_Imports = ( ([String]),(String))
-- cata
sem_Imports :: (Imports) ->
               (T_Imports)
sem_Imports (list) =
    (Prelude.foldr (sem_Imports_Cons) (sem_Imports_Nil) ((Prelude.map sem_Import list)))
sem_Imports_Cons :: (T_Import) ->
                    (T_Imports) ->
                    (T_Imports)
sem_Imports_Cons (hd_) (tl_) =
    let _lhsOlistaImports :: ([String])
        _lhsOout :: (String)
        _hdIlistaImports :: ([String])
        _hdIout :: (String)
        _tlIlistaImports :: ([String])
        _tlIout :: (String)
        ( _hdIlistaImports,_hdIout) =
            (hd_ )
        ( _tlIlistaImports,_tlIout) =
            (tl_ )
        -- "./CondicionesAG.ag"(line 11, column 9)
        (_lhsOlistaImports@_) =
            _hdIlistaImports ++ _tlIlistaImports
        -- "./SalidaContexto.ag"(line 21, column 13)
        (_lhsOout@_) =
            _hdIout ++ "\n" ++ _tlIout
    in  ( _lhsOlistaImports,_lhsOout)
sem_Imports_Nil :: (T_Imports)
sem_Imports_Nil  =
    let _lhsOlistaImports :: ([String])
        _lhsOout :: (String)
        -- "./CondicionesAG.ag"(line 12, column 9)
        (_lhsOlistaImports@_) =
            []
        -- "./SalidaContexto.ag"(line 22, column 13)
        (_lhsOout@_) =
            ""
    in  ( _lhsOlistaImports,_lhsOout)
-- Literal -----------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Literal.LiteralCadena:

-}
data Literal = Literal_LiteralCadena (String)
             deriving ( Show)
-- semantic domain
type T_Literal = ( )
-- cata
sem_Literal :: (Literal) ->
               (T_Literal)
sem_Literal ((Literal_LiteralCadena (_string))) =
    (sem_Literal_LiteralCadena (_string))
sem_Literal_LiteralCadena :: (String) ->
                             (T_Literal)
sem_Literal_LiteralCadena (string_) =
    let 
    in  ( )
-- Llamada -----------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Llamada.Llamada:

-}
data Llamada = Llamada_Llamada (Bool) (String)
             deriving ( Show)
-- semantic domain
type T_Llamada = ( )
-- cata
sem_Llamada :: (Llamada) ->
               (T_Llamada)
sem_Llamada ((Llamada_Llamada (_bool) (_string))) =
    (sem_Llamada_Llamada (_bool) (_string))
sem_Llamada_Llamada :: (Bool) ->
                       (String) ->
                       (T_Llamada)
sem_Llamada_Llamada (bool_) (string_) =
    let 
    in  ( )
-- Method ------------------------------------------------------
{-
   inherited attributes:
      listaIdsH            : [String]

   chained attributes:

   synthesised attributes:
      out                  : String
      resultado            : Bool

-}
{-
   local variables for Method.ConsMethod:

-}
data Method = Method_ConsMethod (String) (Decls)
            deriving ( Show)
-- semantic domain
type T_Method = ([String]) ->
                ( (String),(Bool))
-- cata
sem_Method :: (Method) ->
              (T_Method)
sem_Method ((Method_ConsMethod (_string) (_decls))) =
    (sem_Method_ConsMethod (_string) ((sem_Decls (_decls))))
sem_Method_ConsMethod :: (String) ->
                         (T_Decls) ->
                         (T_Method)
sem_Method_ConsMethod (string_) (decls_) =
    \ _lhsIlistaIdsH ->
        let _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            _declsIout :: (String)
            _declsIresultado :: (Bool)
            _declsOlistaIdsH :: ([String])
            ( _declsIout,_declsIresultado) =
                (decls_ (_declsOlistaIdsH))
            -- "./VerificacionContexto2.ag"(line 33, column 15)
            (_lhsOresultado@_) =
                _declsIresultado
            -- "./SalidaContexto.ag"(line 51, column 15)
            (_lhsOout@_) =
                string_ ++ "\n" ++ "    <%" ++ "\n" ++ _declsIout ++ "\n" ++ "    %>"
            -- copy rule (down)
            (_declsOlistaIdsH@_) =
                _lhsIlistaIdsH
        in  ( _lhsOout,_lhsOresultado)
-- Methods -----------------------------------------------------
{-
   inherited attributes:
      listaIdsH            : [String]

   chained attributes:

   synthesised attributes:
      out                  : String
      resultado            : Bool

-}
{-
   local variables for Methods.Cons:

-}
{-
   local variables for Methods.Nil:

-}
type Methods = [(Method)]
-- semantic domain
type T_Methods = ([String]) ->
                 ( (String),(Bool))
-- cata
sem_Methods :: (Methods) ->
               (T_Methods)
sem_Methods (list) =
    (Prelude.foldr (sem_Methods_Cons) (sem_Methods_Nil) ((Prelude.map sem_Method list)))
sem_Methods_Cons :: (T_Method) ->
                    (T_Methods) ->
                    (T_Methods)
sem_Methods_Cons (hd_) (tl_) =
    \ _lhsIlistaIdsH ->
        let _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            _hdIout :: (String)
            _hdIresultado :: (Bool)
            _hdOlistaIdsH :: ([String])
            _tlIout :: (String)
            _tlIresultado :: (Bool)
            _tlOlistaIdsH :: ([String])
            ( _hdIout,_hdIresultado) =
                (hd_ (_hdOlistaIdsH))
            ( _tlIout,_tlIresultado) =
                (tl_ (_tlOlistaIdsH))
            -- "./VerificacionContexto2.ag"(line 29, column 9)
            (_lhsOresultado@_) =
                _hdIresultado && _tlIresultado
            -- "./SalidaContexto.ag"(line 47, column 13)
            (_lhsOout@_) =
                "    " ++ _hdIout ++ "\n" ++ _tlIout
            -- copy rule (down)
            (_hdOlistaIdsH@_) =
                _lhsIlistaIdsH
            -- copy rule (down)
            (_tlOlistaIdsH@_) =
                _lhsIlistaIdsH
        in  ( _lhsOout,_lhsOresultado)
sem_Methods_Nil :: (T_Methods)
sem_Methods_Nil  =
    \ _lhsIlistaIdsH ->
        let _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            -- "./VerificacionContexto2.ag"(line 30, column 9)
            (_lhsOresultado@_) =
                True
            -- "./SalidaContexto.ag"(line 48, column 13)
            (_lhsOout@_) =
                ""
        in  ( _lhsOout,_lhsOresultado)
-- Module ------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      out                  : String
      resultado            : Bool

-}
{-
   local variables for Module.ConsModule:

-}
data Module = Module_ConsModule (ModuleDeclaration) (ModuleBody)
            deriving ( Show)
-- semantic domain
type T_Module = ( (String),(Bool))
-- cata
sem_Module :: (Module) ->
              (T_Module)
sem_Module ((Module_ConsModule (_moduleDeclaration) (_moduleBody))) =
    (sem_Module_ConsModule ((sem_ModuleDeclaration (_moduleDeclaration))) ((sem_ModuleBody (_moduleBody))))
sem_Module_ConsModule :: (T_ModuleDeclaration) ->
                         (T_ModuleBody) ->
                         (T_Module)
sem_Module_ConsModule (moduleDeclaration_) (moduleBody_) =
    let _lhsOout :: (String)
        _lhsOresultado :: (Bool)
        _moduleDeclarationIout :: (String)
        _moduleBodyIlistaIds :: ([String])
        _moduleBodyIlistaImports :: ([String])
        _moduleBodyIout :: (String)
        _moduleBodyIresultado :: (Bool)
        ( _moduleDeclarationIout) =
            (moduleDeclaration_ )
        ( _moduleBodyIlistaIds,_moduleBodyIlistaImports,_moduleBodyIout,_moduleBodyIresultado) =
            (moduleBody_ )
        -- "./VerificacionContexto2.ag"(line 6, column 15)
        (_lhsOresultado@_) =
            _moduleBodyIresultado
        -- "./SalidaContexto.ag"(line 11, column 15)
        (_lhsOout@_) =
            "module " ++ moduleDeclaration_ ++ " where \n\n" ++ _moduleBodyIout
    in  ( _lhsOout,_lhsOresultado)
-- ModuleBody --------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      listaIds             : [String]
      listaImports         : [String]
      out                  : String
      resultado            : Bool

-}
{-
   local variables for ModuleBody.ConsModBody:

-}
{-
   local variables for ModuleBody.ConsModBody2:

-}
data ModuleBody = ModuleBody_ConsModBody (Imports) (Portal)
                | ModuleBody_ConsModBody2 (Portal)
                deriving ( Show)
-- semantic domain
type T_ModuleBody = ( ([String]),([String]),(String),(Bool))
-- cata
sem_ModuleBody :: (ModuleBody) ->
                  (T_ModuleBody)
sem_ModuleBody ((ModuleBody_ConsModBody (_imports) (_portal))) =
    (sem_ModuleBody_ConsModBody ((sem_Imports (_imports))) ((sem_Portal (_portal))))
sem_ModuleBody ((ModuleBody_ConsModBody2 (_portal))) =
    (sem_ModuleBody_ConsModBody2 ((sem_Portal (_portal))))
sem_ModuleBody_ConsModBody :: (T_Imports) ->
                              (T_Portal) ->
                              (T_ModuleBody)
sem_ModuleBody_ConsModBody (imports_) (portal_) =
    let _lhsOlistaIds :: ([String])
        _lhsOlistaImports :: ([String])
        _lhsOout :: (String)
        _lhsOresultado :: (Bool)
        _importsIlistaImports :: ([String])
        _importsIout :: (String)
        _portalIlistaIds :: ([String])
        _portalIout :: (String)
        _portalIresultado :: (Bool)
        _portalOlistaIdsH :: ([String])
        _portalOlistaImportsH :: ([String])
        ( _importsIlistaImports,_importsIout) =
            (imports_ )
        ( _portalIlistaIds,_portalIout,_portalIresultado) =
            (portal_ (_portalOlistaIdsH) (_portalOlistaImportsH))
        -- "./CondicionesAG.ag"(line 7, column 17)
        (_lhsOlistaImports@_) =
            _importsIlistaImports
        -- "./CondicionesAG.ag"(line 50, column 17)
        (_portalOlistaImportsH@_) =
            _importsIlistaImports
        -- "./CondicionesAG.ag"(line 74, column 17)
        (_portalOlistaIdsH@_) =
            _portalIlistaIds
        -- "./VerificacionContexto2.ag"(line 9, column 17)
        (_lhsOresultado@_) =
            _portalIresultado
        -- "./SalidaContexto.ag"(line 17, column 16)
        (_lhsOout@_) =
            _importsIout ++ _portalIout
        -- copy rule (up)
        (_lhsOlistaIds@_) =
            _portalIlistaIds
    in  ( _lhsOlistaIds,_lhsOlistaImports,_lhsOout,_lhsOresultado)
sem_ModuleBody_ConsModBody2 :: (T_Portal) ->
                               (T_ModuleBody)
sem_ModuleBody_ConsModBody2 (portal_) =
    let _lhsOlistaIds :: ([String])
        _lhsOlistaImports :: ([String])
        _lhsOout :: (String)
        _lhsOresultado :: (Bool)
        _portalIlistaIds :: ([String])
        _portalIout :: (String)
        _portalIresultado :: (Bool)
        _portalOlistaIdsH :: ([String])
        _portalOlistaImportsH :: ([String])
        ( _portalIlistaIds,_portalIout,_portalIresultado) =
            (portal_ (_portalOlistaIdsH) (_portalOlistaImportsH))
        -- "./CondicionesAG.ag"(line 8, column 17)
        (_lhsOlistaImports@_) =
            []
        -- "./CondicionesAG.ag"(line 51, column 17)
        (_portalOlistaImportsH@_) =
            []
        -- "./CondicionesAG.ag"(line 75, column 17)
        (_portalOlistaIdsH@_) =
            _portalIlistaIds
        -- "./VerificacionContexto2.ag"(line 10, column 17)
        (_lhsOresultado@_) =
            _portalIresultado
        -- "./SalidaContexto.ag"(line 18, column 17)
        (_lhsOout@_) =
            ""
        -- copy rule (up)
        (_lhsOlistaIds@_) =
            _portalIlistaIds
    in  ( _lhsOlistaIds,_lhsOlistaImports,_lhsOout,_lhsOresultado)
-- ModuleDeclaration -------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      out                  : String

-}
{-
   local variables for ModuleDeclaration.ModDec:

-}
data ModuleDeclaration = ModuleDeclaration_ModDec (String)
                       deriving ( Show)
-- semantic domain
type T_ModuleDeclaration = ( (String))
-- cata
sem_ModuleDeclaration :: (ModuleDeclaration) ->
                         (T_ModuleDeclaration)
sem_ModuleDeclaration ((ModuleDeclaration_ModDec (_string))) =
    (sem_ModuleDeclaration_ModDec (_string))
sem_ModuleDeclaration_ModDec :: (String) ->
                                (T_ModuleDeclaration)
sem_ModuleDeclaration_ModDec (string_) =
    let _lhsOout :: (String)
        -- "./SalidaContexto.ag"(line 14, column 11)
        (_lhsOout@_) =
            string_
    in  ( _lhsOout)
-- Portal ------------------------------------------------------
{-
   inherited attributes:
      listaIdsH            : [String]
      listaImportsH        : [String]

   chained attributes:

   synthesised attributes:
      listaIds             : [String]
      out                  : String
      resultado            : Bool

-}
{-
   local variables for Portal.ConsPortal:

-}
{-
   local variables for Portal.ConsPortal2:

-}
data Portal = Portal_ConsPortal (String) (PortalBody)
            | Portal_ConsPortal2 (String) (Extend) (PortalBody)
            deriving ( Show)
-- semantic domain
type T_Portal = ([String]) ->
                ([String]) ->
                ( ([String]),(String),(Bool))
-- cata
sem_Portal :: (Portal) ->
              (T_Portal)
sem_Portal ((Portal_ConsPortal (_string) (_portalBody))) =
    (sem_Portal_ConsPortal (_string) ((sem_PortalBody (_portalBody))))
sem_Portal ((Portal_ConsPortal2 (_string) (_extend) (_portalBody))) =
    (sem_Portal_ConsPortal2 (_string) ((sem_Extend (_extend))) ((sem_PortalBody (_portalBody))))
sem_Portal_ConsPortal :: (String) ->
                         (T_PortalBody) ->
                         (T_Portal)
sem_Portal_ConsPortal (string_) (portalBody_) =
    \ _lhsIlistaIdsH
      _lhsIlistaImportsH ->
        let _lhsOlistaIds :: ([String])
            _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            _portalBodyIlistaIds :: ([String])
            _portalBodyIout :: (String)
            _portalBodyIresultado :: (Bool)
            _portalBodyOlistaIdsH :: ([String])
            _portalBodyOlistaImportsH :: ([String])
            ( _portalBodyIlistaIds,_portalBodyIout,_portalBodyIresultado) =
                (portalBody_ (_portalBodyOlistaIdsH) (_portalBodyOlistaImportsH))
            -- "./VerificacionContexto2.ag"(line 13, column 16)
            (_lhsOresultado@_) =
                _portalBodyIresultado
            -- "./SalidaContexto.ag"(line 29, column 16)
            (_lhsOout@_) =
                "\n" ++ "new " ++ string_ ++ "\n<% \n" ++ _portalBodyIout ++ "%>\n"
            -- copy rule (up)
            (_lhsOlistaIds@_) =
                _portalBodyIlistaIds
            -- copy rule (down)
            (_portalBodyOlistaIdsH@_) =
                _lhsIlistaIdsH
            -- copy rule (down)
            (_portalBodyOlistaImportsH@_) =
                _lhsIlistaImportsH
        in  ( _lhsOlistaIds,_lhsOout,_lhsOresultado)
sem_Portal_ConsPortal2 :: (String) ->
                          (T_Extend) ->
                          (T_PortalBody) ->
                          (T_Portal)
sem_Portal_ConsPortal2 (string_) (extend_) (portalBody_) =
    \ _lhsIlistaIdsH
      _lhsIlistaImportsH ->
        let _lhsOlistaIds :: ([String])
            _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            _extendIout :: (String)
            _portalBodyIlistaIds :: ([String])
            _portalBodyIout :: (String)
            _portalBodyIresultado :: (Bool)
            _portalBodyOlistaIdsH :: ([String])
            _portalBodyOlistaImportsH :: ([String])
            ( _extendIout) =
                (extend_ )
            ( _portalBodyIlistaIds,_portalBodyIout,_portalBodyIresultado) =
                (portalBody_ (_portalBodyOlistaIdsH) (_portalBodyOlistaImportsH))
            -- "./VerificacionContexto2.ag"(line 14, column 16)
            (_lhsOresultado@_) =
                _portalBodyIresultado
            -- "./SalidaContexto.ag"(line 30, column 16)
            (_lhsOout@_) =
                "\n" ++ "new " ++ string_ ++ " ( " ++ _extendIout ++ " ) \n<% \n" ++ _portalBodyIout ++ "%>\n"
            -- copy rule (up)
            (_lhsOlistaIds@_) =
                _portalBodyIlistaIds
            -- copy rule (down)
            (_portalBodyOlistaIdsH@_) =
                _lhsIlistaIdsH
            -- copy rule (down)
            (_portalBodyOlistaImportsH@_) =
                _lhsIlistaImportsH
        in  ( _lhsOlistaIds,_lhsOout,_lhsOresultado)
-- PortalBody --------------------------------------------------
{-
   inherited attributes:
      listaIdsH            : [String]
      listaImportsH        : [String]

   chained attributes:

   synthesised attributes:
      listaIds             : [String]
      out                  : String
      resultado            : Bool

-}
{-
   local variables for PortalBody.ConsPortalBody:

-}
data PortalBody = PortalBody_ConsPortalBody (TopDecls) (Methods)
                deriving ( Show)
-- semantic domain
type T_PortalBody = ([String]) ->
                    ([String]) ->
                    ( ([String]),(String),(Bool))
-- cata
sem_PortalBody :: (PortalBody) ->
                  (T_PortalBody)
sem_PortalBody ((PortalBody_ConsPortalBody (_topDecls) (_methods))) =
    (sem_PortalBody_ConsPortalBody ((sem_TopDecls (_topDecls))) ((sem_Methods (_methods))))
sem_PortalBody_ConsPortalBody :: (T_TopDecls) ->
                                 (T_Methods) ->
                                 (T_PortalBody)
sem_PortalBody_ConsPortalBody (topDecls_) (methods_) =
    \ _lhsIlistaIdsH
      _lhsIlistaImportsH ->
        let _lhsOlistaIds :: ([String])
            _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            _topDeclsIlistaIds :: ([String])
            _topDeclsIlistaTypes :: ([String])
            _topDeclsIout :: (String)
            _topDeclsIresultado :: (Bool)
            _topDeclsOlistaIdsH :: ([String])
            _topDeclsOlistaImportsH :: ([String])
            _topDeclsOlistaTypesH :: ([String])
            _methodsIout :: (String)
            _methodsIresultado :: (Bool)
            _methodsOlistaIdsH :: ([String])
            ( _topDeclsIlistaIds,_topDeclsIlistaTypes,_topDeclsIout,_topDeclsIresultado) =
                (topDecls_ (_topDeclsOlistaIdsH) (_topDeclsOlistaImportsH) (_topDeclsOlistaTypesH))
            ( _methodsIout,_methodsIresultado) =
                (methods_ (_methodsOlistaIdsH))
            -- "./CondicionesAG.ag"(line 69, column 35)
            (_topDeclsOlistaTypesH@_) =
                _topDeclsIlistaTypes
            -- "./CondicionesAG.ag"(line 68, column 19)
            (_topDeclsOlistaIdsH@_) =
                _topDeclsIlistaIds
            -- "./VerificacionContexto2.ag"(line 17, column 19)
            (_lhsOresultado@_) =
                _topDeclsIresultado && _methodsIresultado
            -- "./SalidaContexto.ag"(line 36, column 19)
            (_lhsOout@_) =
                _topDeclsIout ++ _methodsIout
            -- copy rule (up)
            (_lhsOlistaIds@_) =
                _topDeclsIlistaIds
            -- copy rule (down)
            (_topDeclsOlistaImportsH@_) =
                _lhsIlistaImportsH
            -- copy rule (down)
            (_methodsOlistaIdsH@_) =
                _lhsIlistaIdsH
        in  ( _lhsOlistaIds,_lhsOout,_lhsOresultado)
-- Root --------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      out                  : IO ()

-}
{-
   local variables for Root.Root:

-}
data Root = Root_Root (Module)
          deriving ( Show)
-- semantic domain
type T_Root = ( (IO ()))
-- cata
sem_Root :: (Root) ->
            (T_Root)
sem_Root ((Root_Root (_module))) =
    (sem_Root_Root ((sem_Module (_module))))
sem_Root_Root :: (T_Module) ->
                 (T_Root)
sem_Root_Root (module_) =
    let _lhsOout :: (IO ())
        _moduleIout :: (String)
        _moduleIresultado :: (Bool)
        ( _moduleIout,_moduleIresultado) =
            (module_ )
        -- "./SalidaContexto.ag"(line 6, column 9)
        (_lhsOout@_) =
            putStrLn (if not _moduleIresultado then _moduleIout ++ "\n" ++ "ERROR" else "OK, successfull compilation")
    in  ( _lhsOout)
-- TopDecl -----------------------------------------------------
{-
   inherited attributes:
      listaIdsH            : [String]
      listaImportsH        : [String]
      listaTypesH          : [String]

   chained attributes:

   synthesised attributes:
      listaIds             : [String]
      listaTypes           : [String]
      out                  : String
      resultado            : Bool

-}
{-
   local variables for TopDecl.ConsTopDecl:
      errorTopDecl

-}
data TopDecl = TopDecl_ConsTopDecl (String) (String)
             deriving ( Show)
-- semantic domain
type T_TopDecl = ([String]) ->
                 ([String]) ->
                 ([String]) ->
                 ( ([String]),([String]),(String),(Bool))
-- cata
sem_TopDecl :: (TopDecl) ->
               (T_TopDecl)
sem_TopDecl ((TopDecl_ConsTopDecl (_nomAttr) (_nomType))) =
    (sem_TopDecl_ConsTopDecl (_nomAttr) (_nomType))
sem_TopDecl_ConsTopDecl :: (String) ->
                           (String) ->
                           (T_TopDecl)
sem_TopDecl_ConsTopDecl (nomAttr_) (nomType_) =
    \ _lhsIlistaIdsH
      _lhsIlistaImportsH
      _lhsIlistaTypesH ->
        let _lhsOlistaIds :: ([String])
            _lhsOlistaTypes :: ([String])
            _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            -- "./CondicionesAG.ag"(line 27, column 16)
            (_lhsOlistaIds@_) =
                [nomAttr_]
            -- "./CondicionesAG.ag"(line 38, column 16)
            (_lhsOlistaTypes@_) =
                [nomType_]
            -- "./VerificacionContexto2.ag"(line 26, column 28)
            (_lhsOresultado@_) =
                _errorTopDecl
            -- "./VerificacionContexto2.ag"(line 25, column 16)
            (_errorTopDecl@_) =
                nomType_ `elem` _lhsIlistaImportsH
            -- "./SalidaContexto.ag"(line 43, column 16)
            (_lhsOout@_) =
                "type " ++ nomAttr_ ++ " = " ++ nomType_ ++ ";" ++ if not _errorTopDecl then " <- Tipo no declarado o no se a importado" else ""
        in  ( _lhsOlistaIds,_lhsOlistaTypes,_lhsOout,_lhsOresultado)
-- TopDecls ----------------------------------------------------
{-
   inherited attributes:
      listaIdsH            : [String]
      listaImportsH        : [String]
      listaTypesH          : [String]

   chained attributes:

   synthesised attributes:
      listaIds             : [String]
      listaTypes           : [String]
      out                  : String
      resultado            : Bool

-}
{-
   local variables for TopDecls.Cons:

-}
{-
   local variables for TopDecls.Nil:

-}
type TopDecls = [(TopDecl)]
-- semantic domain
type T_TopDecls = ([String]) ->
                  ([String]) ->
                  ([String]) ->
                  ( ([String]),([String]),(String),(Bool))
-- cata
sem_TopDecls :: (TopDecls) ->
                (T_TopDecls)
sem_TopDecls (list) =
    (Prelude.foldr (sem_TopDecls_Cons) (sem_TopDecls_Nil) ((Prelude.map sem_TopDecl list)))
sem_TopDecls_Cons :: (T_TopDecl) ->
                     (T_TopDecls) ->
                     (T_TopDecls)
sem_TopDecls_Cons (hd_) (tl_) =
    \ _lhsIlistaIdsH
      _lhsIlistaImportsH
      _lhsIlistaTypesH ->
        let _lhsOlistaIds :: ([String])
            _lhsOlistaTypes :: ([String])
            _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            _hdIlistaIds :: ([String])
            _hdIlistaTypes :: ([String])
            _hdIout :: (String)
            _hdIresultado :: (Bool)
            _hdOlistaIdsH :: ([String])
            _hdOlistaImportsH :: ([String])
            _hdOlistaTypesH :: ([String])
            _tlIlistaIds :: ([String])
            _tlIlistaTypes :: ([String])
            _tlIout :: (String)
            _tlIresultado :: (Bool)
            _tlOlistaIdsH :: ([String])
            _tlOlistaImportsH :: ([String])
            _tlOlistaTypesH :: ([String])
            ( _hdIlistaIds,_hdIlistaTypes,_hdIout,_hdIresultado) =
                (hd_ (_hdOlistaIdsH) (_hdOlistaImportsH) (_hdOlistaTypesH))
            ( _tlIlistaIds,_tlIlistaTypes,_tlIout,_tlIresultado) =
                (tl_ (_tlOlistaIdsH) (_tlOlistaImportsH) (_tlOlistaTypesH))
            -- "./CondicionesAG.ag"(line 23, column 9)
            (_lhsOlistaIds@_) =
                _hdIlistaIds ++ _tlIlistaIds
            -- "./CondicionesAG.ag"(line 34, column 9)
            (_lhsOlistaTypes@_) =
                _hdIlistaTypes ++ _tlIlistaTypes
            -- "./VerificacionContexto2.ag"(line 20, column 9)
            (_lhsOresultado@_) =
                _hdIresultado && _tlIresultado
            -- "./SalidaContexto.ag"(line 39, column 13)
            (_lhsOout@_) =
                "    " ++ _hdIout ++ "\n" ++ _tlIout
            -- copy rule (down)
            (_hdOlistaIdsH@_) =
                _lhsIlistaIdsH
            -- copy rule (down)
            (_hdOlistaImportsH@_) =
                _lhsIlistaImportsH
            -- copy rule (down)
            (_hdOlistaTypesH@_) =
                _lhsIlistaTypesH
            -- copy rule (down)
            (_tlOlistaIdsH@_) =
                _lhsIlistaIdsH
            -- copy rule (down)
            (_tlOlistaImportsH@_) =
                _lhsIlistaImportsH
            -- copy rule (down)
            (_tlOlistaTypesH@_) =
                _lhsIlistaTypesH
        in  ( _lhsOlistaIds,_lhsOlistaTypes,_lhsOout,_lhsOresultado)
sem_TopDecls_Nil :: (T_TopDecls)
sem_TopDecls_Nil  =
    \ _lhsIlistaIdsH
      _lhsIlistaImportsH
      _lhsIlistaTypesH ->
        let _lhsOlistaIds :: ([String])
            _lhsOlistaTypes :: ([String])
            _lhsOout :: (String)
            _lhsOresultado :: (Bool)
            -- "./CondicionesAG.ag"(line 24, column 9)
            (_lhsOlistaIds@_) =
                []
            -- "./CondicionesAG.ag"(line 35, column 9)
            (_lhsOlistaTypes@_) =
                []
            -- "./VerificacionContexto2.ag"(line 21, column 9)
            (_lhsOresultado@_) =
                True
            -- "./SalidaContexto.ag"(line 40, column 13)
            (_lhsOout@_) =
                ""
        in  ( _lhsOlistaIds,_lhsOlistaTypes,_lhsOout,_lhsOresultado)
-- Type --------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      out                  : String

-}
{-
   local variables for Type.ConsType:

-}
data Type = Type_ConsType (String)
          deriving ( Show)
-- semantic domain
type T_Type = ( (String))
-- cata
sem_Type :: (Type) ->
            (T_Type)
sem_Type ((Type_ConsType (_string))) =
    (sem_Type_ConsType (_string))
sem_Type_ConsType :: (String) ->
                     (T_Type)
sem_Type_ConsType (string_) =
    let _lhsOout :: (String)
        -- "./SalidaContexto.ag"(line 90, column 13)
        (_lhsOout@_) =
            string_
    in  ( _lhsOout)


