-- do not edit; automatically generated by UU.AG
module TreeAG where

main = sem_Root ejemplo

ejemplo = Root_Root(Tree_Rama (Tree_Rama (Tree_Hoja 2) 
			(Tree_Rama (Tree_Hoja 5) (Tree_Hoja 20))) (Tree_Hoja 10))
-- Root --------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      lista                : [Int]

-}
{-
   local variables for Root.Root:

-}
data Root = Root_Root (Tree)
-- semantic domain
type T_Root = ( ([Int]))
-- cata
sem_Root :: (Root) ->
            (T_Root)
sem_Root ((Root_Root (_tree))) =
    (sem_Root_Root ((sem_Tree (_tree))))
sem_Root_Root :: (T_Tree) ->
                 (T_Root)
sem_Root_Root (tree_) =
    let _lhsOlista :: ([Int])
        _treeIlista :: ([Int])
        ( _treeIlista) =
            (tree_ )
        -- copy rule (up)
        (_lhsOlista@_) =
            _treeIlista
    in  ( _lhsOlista)
-- Tree --------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      lista                : [Int]

-}
{-
   local variables for Tree.Hoja:

-}
{-
   local variables for Tree.Rama:

-}
data Tree = Tree_Hoja (Int)
          | Tree_Rama (Tree) (Tree)
-- semantic domain
type T_Tree = ( ([Int]))
-- cata
sem_Tree :: (Tree) ->
            (T_Tree)
sem_Tree ((Tree_Hoja (_val))) =
    (sem_Tree_Hoja (_val))
sem_Tree ((Tree_Rama (_izq) (_der))) =
    (sem_Tree_Rama ((sem_Tree (_izq))) ((sem_Tree (_der))))
sem_Tree_Hoja :: (Int) ->
                 (T_Tree)
sem_Tree_Hoja (val_) =
    let _lhsOlista :: ([Int])
        -- "/home/benjamin/workspace/GenericPortlet/AG/TreeAG.ag"(line 30, column 9)
        (_lhsOlista@_) =
            [val_]
    in  ( _lhsOlista)
sem_Tree_Rama :: (T_Tree) ->
                 (T_Tree) ->
                 (T_Tree)
sem_Tree_Rama (izq_) (der_) =
    let _lhsOlista :: ([Int])
        _izqIlista :: ([Int])
        _derIlista :: ([Int])
        ( _izqIlista) =
            (izq_ )
        ( _derIlista) =
            (der_ )
        -- "/home/benjamin/workspace/GenericPortlet/AG/TreeAG.ag"(line 31, column 9)
        (_lhsOlista@_) =
            (_izqIlista)++(_derIlista)
    in  ( _lhsOlista)


